### ISSUE TITLE
Random panics whenever the GC is invoked

### ISSUE THREAD

**Issue by kalbasit** [zenhack/go.notmuch#11]
While working on my project (which is BTW now accessible at [Gmuch](https://github.com/gmuch/gmuch)) I discovered that go.notmuch is panicking whenever the GC is invoked (either by runtime.GC() or by Go itself). This has happened when I asked Gmuch to load the latest 5000 threads:

```
kalbasit@cratos ~/code/src/github.com/gmuch/gmuch [master *] ± % time http POST localhost:7080/query q=tag:inbox limit:=5000

http: error: ConnectionError: ('Connection aborted.', BadStatusLine("''",))
http --print=HhBb POST localhost:7080/query q=tag:inbox limit:=5000  0.13s user 0.06s system 3% cpu 5.556 total
```

and the panic:

```
kalbasit@cratos ~/code/src/github.com/gmuch/gmuch [master *] ± % go run cmd/gmuch/main.go --db-path=/Users/kalbasit/.mail
listen=:7080 caller=main.go:72 msg=HTTP addr=:7080
listen=:7080 caller=log.go:43 method=thread id=0000000000020ab3 took=30.917227ms
listen=:7080 caller=log.go:26 method=query query=tag:inbox offset=0 limit=100 took=483.272983ms
listen=:7080 caller=log.go:43 method=thread id=0000000000020c5c took=22.619513ms
SIGABRT: abort
PC=0x7fff9589a0ae m=7
signal arrived during cgo execution

goroutine 19 [syscall, locked to thread]:
runtime.cgocall(0x4002fc0, 0xc82002af18, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/cgocall.go:120 +0x11b fp=0xc82002aee8 sp=0xc82002aeb8
github.com/gmuch/gmuch/vendor/github.com/zenhack/go%2enotmuch._Cfunc_notmuch_tags_destroy(0x64062d0)
        github.com/gmuch/gmuch/vendor/github.com/zenhack/go.notmuch/_obj/_cgo_gotypes.go:689 +0x31 fp=0xc82002af18 sp=0xc82002aee8
github.com/gmuch/gmuch/vendor/github.com/zenhack/go%2enotmuch.(*Message).Tags.func1(0xc82012bc20)
        /Users/kalbasit/code/src/github.com/gmuch/gmuch/vendor/github.com/zenhack/go.notmuch/message.go:88 +0x24 fp=0xc82002af28 sp=0xc82002af18
runtime.call32(0x0, 0x44fe278, 0xc820104030, 0x1000000010)
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:437 +0x3e fp=0xc82002af50 sp=0xc82002af28
runtime.runfinq()
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/mfinal.go:196 +0x292 fp=0xc82002afc0 sp=0xc82002af50
runtime.goexit()
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002afc8 sp=0xc82002afc0
created by runtime.createfing
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/mfinal.go:135 +0x60

goroutine 1 [IO wait]:
net.runtime_pollWait(0x4f45e30, 0x72, 0xc8200780a0)
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200e6920, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200e6920, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8200e68c0, 0x0, 0x4f45f28, 0xc8203d4700)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200900b0, 0x4054720, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8200900b0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc820076900, 0x4f45ef0, 0xc8200900b0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820076900, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0x4449470, 0x5, 0x4f44e58, 0xc82007fda0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1967 +0x8f
main.main()
        /Users/kalbasit/code/src/github.com/gmuch/gmuch/cmd/gmuch/main.go:73 +0xed7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 32 [runnable, locked to thread]:
github.com/gmuch/gmuch/vendor/github.com/zenhack/go%2enotmuch._Cfunc_notmuch_threads_get(0x4d589f0, 0x6430990)
        github.com/gmuch/gmuch/vendor/github.com/zenhack/go.notmuch/_obj/_cgo_gotypes.go:881 +0x36
github.com/gmuch/gmuch/vendor/github.com/zenhack/go%2enotmuch.(*Threads).get(0xc8203d10e0, 0xc800000001)
        /Users/kalbasit/code/src/github.com/gmuch/gmuch/vendor/github.com/zenhack/go.notmuch/threads.go:35 +0x28
github.com/gmuch/gmuch/vendor/github.com/zenhack/go%2enotmuch.(*Threads).Next(0xc8203d10e0, 0xc82004f648, 0x3)
        /Users/kalbasit/code/src/github.com/gmuch/gmuch/vendor/github.com/zenhack/go.notmuch/threads.go:29 +0x47
github.com/gmuch/gmuch.(*Gmuch).Query(0xc820093ae0, 0xc8203d10c0, 0x9, 0x0, 0x1388, 0x0, 0x0, 0x0)
        /Users/kalbasit/code/src/github.com/gmuch/gmuch/query.go:31 +0x24e
github.com/gmuch/gmuch/server.logMiddleware.Query(0x4f449c0, 0xc82007faa0, 0x4f44b00, 0xc820093ae0, 0xc8203d10c0, 0x9, 0x0, 0x1388, 0x0, 0x0, ...)
        /Users/kalbasit/code/src/github.com/gmuch/gmuch/server/log.go:37 +0x155
github.com/gmuch/gmuch/server.(*logMiddleware).Query(0xc820093b20, 0xc8203d10c0, 0x9, 0x0, 0x1388, 0x4f44ad0, 0x0, 0x0)
        <autogenerated>:5 +0xd3
github.com/gmuch/gmuch/server.instrumentingMiddleware.Query(0x4f44a40, 0xc820079e30, 0x4f44ad0, 0xc820093ac0, 0x4f44b30, 0xc820093b20, 0xc8203d10c0, 0x9, 0x0, 0x1388, ...)
        /Users/kalbasit/code/src/github.com/gmuch/gmuch/server/instrumenting.go:35 +0x151
github.com/gmuch/gmuch/server.(*instrumentingMiddleware).Query(0xc82007fd40, 0xc8203d10c0, 0x9, 0x0, 0x1388, 0xc8203d4780, 0x0, 0x0)
        <autogenerated>:3 +0xd9
github.com/gmuch/gmuch.EndpointenizeQuery.func1(0x4f46160, 0xc8203913c0, 0x43df420, 0xc8203d47a0, 0x0, 0x0, 0x0, 0x0)
        /Users/kalbasit/code/src/github.com/gmuch/gmuch/endpoint.go:13 +0x116
github.com/gmuch/gmuch/vendor/github.com/go-kit/kit/transport/http.Server.ServeHTTP(0x4f44b90, 0xc820078bd0, 0xc820093b40, 0x44fe210, 0x44fe220, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/kalbasit/code/src/github.com/gmuch/gmuch/vendor/github.com/go-kit/kit/transport/http/server.go:93 +0x418
github.com/gmuch/gmuch/vendor/github.com/go-kit/kit/transport/http.(*Server).ServeHTTP(0xc8200e6380, 0x4f460f8, 0xc8200c7550, 0xc8203d62a0)
        <autogenerated>:2 +0xd1
net/http.(*ServeMux).ServeHTTP(0xc82007fda0, 0x4f460f8, 0xc8200c7550, 0xc8203d62a0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc820076900, 0x4f460f8, 0xc8200c7550, 0xc8203d62a0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200c74a0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1910 +0x3f6

rax    0x0
rbx    0x6
rcx    0x70000030fd58
rdx    0x0
rdi    0x1e03
rsi    0x6
rbp    0x70000030fd80
rsp    0x70000030fd58
r8     0xc820068480
r9     0xc82002aeb0
r10    0x8000000
r11    0x206
r12    0x64062d0
r13    0x61660089df10
r14    0x700000310000
r15    0x0
rip    0x7fff9589a0ae
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
exit status 2
```

I made a reproducible test by randomly invoking the GC in the tests. See kalbasit/go.notmuch@491e3a3b842501c99f3e70af92da0f8fd215486b

**Comment by zenhack** [comment]
I played around with this a bit, made a couple of observations:
1. We're calling notmuch_database_destroy both from Close() and as a finalizer. While notmuch.h says it's okay to call notmuch_database_close twice, it's not obvious that this extends to _destroy; The function is just a close followed by a talloc_free (https://talloc.samba.org/talloc/doc/html/group__talloc.html#ga3de117af6571f568866ec311bcd75f86), and it sounds like the latter doesn't handle double-frees gracefully. Also, when I run the tests, it's always database_destroy that's in the stack traces, unless I comment out those finalizers and something else comes up.
2. FindMessageByFilename doesn't store a reference to the db in the Message (indeed, the message type has no field for a database). This makes it possible for the GC to reclaim the database before that message, and it seems probable that calling the finalizer on the message later will go badly.

(2) makes me think it's worth some time cleaning up the object creation code; I'm not keen on staring at the code long enough to be confident that I've plugged each and every hole. I'll spend a bit of time on it.

This also brings up another concern: If it is actually invalid to free the children of objects that have already been freed, then we're violating this constraint _everywhere_ (in fact, the semantics of SetFinalizer are enforcing this). I'll take this into account when redesigning.

I'll probably end up cherry-picking your test case(s) while I'm working on this.

**Comment by zenhack** [comment]
Ack, scratch the last comment about us consistently violating the ordering constraint, things should actually be freed child-first (misread things... thought that seemed weird :/), but it does cause a problem if we want to explicitly close the database.

**Comment by kalbasit** [comment]
this Gist is also worth a look: https://gist.github.com/dwbuiten/c9865c4afb38f482702e

**Comment by zenhack** [comment]
Quoting Wael M. Nasreddine (2015-10-03 13:38:37)

>    this Gist is also worth a look:

Thanks for the link. I will have a look.

**Comment by kalbasit** [comment]
So about the `notmuch_database_destroy` I did try multiple `db.Close()` in the example before adding the `runtime.SetFinalizer` for it. That being said, after reading the above-mentioned Gist, I feel like we should replace all of the `runtime.SetFinalizer` with a `Close` method that the caller will have to call (for db, threads, thread, messages and message).

**Comment by zenhack** [comment]
I also misread the implementation of Close() the other night, it's not calling _destroy anyway. But yeah, I think you're right. Having Close() methods on everything is at least consistent with what `database/sql` does.

I can take the lead on fixing this; I'd like to actually do a bit of hacking on my own library for once. :P

**Comment by kalbasit** [comment]
That's fine by me lol :+1:

**Comment by kalbasit** [comment]
ok so looking at 

```
=== RUN   TestOpenNotFound
Error opening database at /not-found/.notmuch: No such file or directory
--- PASS: TestOpenNotFound (0.00s)
=== RUN   TestCreate
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x18 pc=0x4d378bf]

runtime stack:
runtime.throw(0x4271560, 0x2a)
    /usr/local/Cellar/go/1.5.1/libexec/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
    /usr/local/Cellar/go/1.5.1/libexec/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 18 [syscall, locked to thread]:
runtime.cgocall(0x4025da0, 0xc820028708, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/runtime/cgocall.go:120 +0xc2 fp=0xc8200286d8 sp=0xc8200286b0
github.com/zenhack/go%2enotmuch._Cfunc_notmuch_database_destroy(0x0, 0x0)
    github.com/zenhack/go.notmuch/_test/_obj_test/_cgo_gotypes.go:207 +0x57 fp=0xc820028708 sp=0xc8200286d8
```

notmuch_database_destroy in `github.com/zenhack/go%2enotmuch._Cfunc_notmuch_database_destroy(0x0, 0x0)` is receiving a NULL so probably the cptr was either free'd C side or GC'd prior to calling finalizer. I'll let you try solving this yourself, however I think you should merge #10 first to get the full picture.

also see https://groups.google.com/forum/#!topic/golang-nuts/65pdWIYga4E

**Comment by zenhack** [comment]
Alright, I'll have a look at #10 first.

**Comment by zenhack** [comment]
So, the crappy thing about just adding Close() to everything is that now you can't do `db.NewQuery("foo").Threads()`, or you leak the query. This may affect my opinion. What are your thoughts?

One approach we could take is to try to fix the bugs we have now while keeping the finalizers, and supply the close methods as well for users who need more control over memory usage.

**Comment by zenhack** [comment]
fwiw, the memory taken up by the query object itself is pretty small; a couple of flags, a pointer to the db, and a list of excluded search terms (unlikely to be large). For most applications the GC's guess about it's size won't be _too_ far off. The other objects are bigger and more likely to cause trouble, but the above idiom is probably fine as far as being able to let the GC deal with it.

**Comment by kalbasit** [comment]
I see, well I'm fine with that as long as the panics are not occurring. When you replaced `runtime.SetFinalizer` with `Close` did it work?

**Comment by zenhack** [comment]
Quoting Wael M. Nasreddine (2015-10-06 19:37:13)

>    I see, well I'm fine with that as long as the panics are not occurring.
>    When you replaced runtime.SetFinalizer with Close did it work?

The tests passed on my local machine; I pushed to a branch which is
referencing this bug. I'm going to do another variant behaves as I
described. If that one passes the test, I'll submit a pr and ask you to
have a look.

**Comment by zenhack** [comment]
Now that #12 is merged, I'm going to close this.
