### ISSUE TITLE
.Slice() methods on iterator types.

### ISSUE THREAD

**Issue by zenhack** [zenhack/go.notmuch#13]
...Which returns a slice of the sequence.

Particularly with tags we're re-implementing this repeatedly in the test-suite.

**Comment by zenhack** [comment]
I think what I'd like to do here is set a date, say 3 weeks from now (somewhat arbitrary), to give us a little time to play with the library, and if by then it hasn't become clear that this is something we definitely want, or what it should look like, we just close this without implementing.

3 Weeks would put us at Nov. 7th.

//cc @kalbasit

**Comment by zenhack** [comment]
I'm going to go ahead and close. Haven't really done much playing with the library, but eh...

**Comment by kalbasit** [comment]
same here. Still blocked on another issues, I will re-visit when I do.
