### ISSUE TITLE
Rewrite notmuchmail in Go

### ISSUE THREAD

**Issue by kalbasit** [zenhack/go.notmuch#14]
Today I'm wondering if it would be a much better investment to write the **core** of notmuch (indexing and searching) using [bleve](https://github.com/blevesearch/bleve) or ElasticSearch (Best would be a swappable backend). Thoughts?

**Comment by zenhack** [comment]
What you're talking about is it's own project, though not necessarily a bad one. I think it's solidly out of scope for this little language binding though; I'm going to close.

**Comment by kalbasit** [comment]
Oh I didn't mean part of this project but thought to be a place to speculate as we don't have mailing list or any other place to talk. Although, not a bad candidate for an email thread, my email is available on my profile.

**Comment by zenhack** [comment]
Fair enough. It sounds like a fun project, but frankly I've got enough on my plate as is. If you're interested, go for it --- I'd be curious to see what you'd come up with. I probably won't have the time to put into it though.
