### ISSUE TITLE
There's a deadlock somewhere.

### ISSUE THREAD

**Issue by zenhack** [zenhack/go.notmuch#15]
https://travis-ci.org/zenhack/go.notmuch/builds/85976525

The tests passed fine on my desktop, and the branch I pushed to before merging to master. I can't repeat the failure on my desktop, but I seem to be able to do so on one of my other machines. I've yet to dig into this.

**Comment by kalbasit** [comment]
Actually that's a Travis issue. Compare [55.1](https://travis-ci.org/zenhack/go.notmuch/jobs/85976526) to [55.2](https://travis-ci.org/zenhack/go.notmuch/jobs/85976527) and you'll see that the test did not even start.

**Comment by zenhack** [comment]
Okay, yeah, good call --- it's stopping before it even gets to running the tests. I thought I'd gotten something similar on my other machine last night, but I can't reproduce it now. It's possible something weird was just going on with my machine. I'll close; I don't really feel like going on a wild goose chase trying to reproduce this.
