### ISSUE TITLE
Document how to run the tests

### ISSUE THREAD

**Issue by brunnre8** [zenhack/go.notmuch#17]
The testsuit as is fails if one clones the repo as is.
It can't even open up the database at first: `Error opening database at /home/reto/sourcecode/go.notmuch/fixtures/database-v1/.notmuch: No such file or directory`

Now, even if one does create that database, it still fails as all the emails it expects are not present, yielding errors like
```
--- FAIL: TestFindMessage (0.00s)
    db_test.go:158: db.FindMessage("87iqd9rn3l.fsf@vertex.dottedmag"): unexpected error: not found
```

Could you please add the corresponding messages you expect in the test to the repo?

**Comment by zenhack** [comment]
The test data should be fetched if you type `make test`. This should be documented though, so I'm going to change the title of this issue to reflect that.

**Comment by brunnre8** [comment]
Ah, wasn't looking for a Makefile... sorry for the noise
