### ISSUE TITLE
Cross Compile does not work

### ISSUE THREAD

**Issue by JohannesKaufmann** [zenhack/go.notmuch#26]
I developed a small email program based on your awesome library 💯. Thanks alot for your work! It was such a hassle dealing with IMAP and then Maildir until I found notmuch.  

Now I want to deploy to a small server, so I have to cross compile for linux on a mac.

- `go build` works.
- `GOOS=linux GOARCH=amd64 go build` does not work (`undefined: notmuch.DB`).
- commenting out the notmuch parts and running `GOOS=linux GOARCH=amd64 go build` again works. 

- `CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build` gives me a bunch of errors about the sqlite3-bindings.

- using [xgo](https://github.com/karalabe/xgo) `xgo --targets=linux/amd64 .` fails with the following message:

```
...

# github.com/zenhack/go.notmuch
/go/pkg/mod/github.com/zenhack/go.notmuch@v0.0.0-20190821052706-5a1961965cfb/configList.go:9:22: fatal error: notmuch.h: No such file or directory
 // #include <notmuch.h>
                      ^
compilation terminated.
2020/05/28 13:54:27 Failed to cross compile package: exit status 2.
```

- `xgo --deps=https://notmuchmail.org/releases/LATEST-notmuch-0.29.3.tar.xz --targets=linux/amd64 .` still fails with the above message.

-----

To be honest, I don't know what to try now 🤷‍♂️. The last option is pulling the source code onto a Linux machine and then compiling there. But this is also annoying.

@zenhack  Do you have any ideas?

**Comment by brunnre8** [comment]
well, do you have a working c compiler for your target architecture?
This library uses C and C doesn't cross compile as easily as go alone.

**Comment by zenhack** [comment]
@brunnre8, supposedly `xgo` should set that up itself, though I was not previously familiar with the tool.

@JohannesKaufmann, can you attach the *full* build log, not just the error at the end?

**Comment by JohannesKaufmann** [comment]
Thanks for fast response 🤩

----------

I should have the c compiler through Xcode but I have no experience with it yet.

<details>
  <summary>gcc --version</summary>
  <pre><code>
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
  </pre></code>
</details>


<details>
  <summary>cc --version</summary>
  <pre><code>
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
  </pre></code>
</details>


But that should not be necessary with xgo.

> All the necessary Go tool-chains, C cross compilers and platform headers/libraries have been assembled into a single Docker container

----------



I'm now using [your example](https://github.com/zenhack/go.notmuch/blob/master/example/main.go) from this repo. So no other dependencies.

<details>
  <summary>CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build</summary>
 <pre><code>
# github.com/JohannesKaufmann/notmuchexample
/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: ignoring file /var/folders/1_/67t9ylqs1sq166166pc8m4mr0000gn/T/go-link-093818949/go.o, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
Undefined symbols for architecture x86_64:
  "__cgo_topofstack", referenced from:
      __cgo_b6b57930d1df_Cfunc_notmuch_config_list_key in 000001.o
      __cgo_b6b57930d1df_Cfunc_notmuch_config_list_valid in 000001.o
      __cgo_b6b57930d1df_Cfunc_notmuch_config_list_value in 000001.o
      __cgo_b6b57930d1df_Cfunc_notmuch_database_begin_atomic in 000002.o
      __cgo_b6b57930d1df_Cfunc_notmuch_database_compact in 000002.o
      __cgo_b6b57930d1df_Cfunc_notmuch_database_create in 000002.o
      __cgo_b6b57930d1df_Cfunc_notmuch_database_destroy in 000002.o
      ...
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</code></pre>
</details>


<details>
  <summary>xgo --targets=linux/amd64 .</summary>
 <pre><code>
Checking docker installation...
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Checking for required docker image karalabe/xgo-latest... found.
Cross compiling github.com/JohannesKaufmann/notmuchexample...
Building locally github.com/JohannesKaufmann/notmuchexample...
Compiling for linux/amd64...
\# github.com/zenhack/go.notmuch
\../../zenhack/go.notmuch/configList.go:9:22: fatal error: notmuch.h: No such file or directory
 // #include <notmuch.h>
                      ^
compilation terminated.
2020/05/29 11:23:20 Failed to cross compile package: exit status 2.
</code></pre>
</details>



<details>
  <summary>xgo --targets=linux/amd64 -v -x .</summary>
 <pre><code>
Checking docker installation...
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Checking for required docker image karalabe/xgo-latest... found.
Cross compiling github.com/JohannesKaufmann/notmuchexample...
Building locally github.com/JohannesKaufmann/notmuchexample...
Compiling for linux/amd64...
WORK=/tmp/go-build647325213
github.com/zenhack/go.notmuch
mkdir -p $WORK/b033/
cd /ext-go/1/src/github.com/zenhack/go.notmuch
CGO_LDFLAGS='"-g" "-O2" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch"' /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/b033/ -importpath github.com/zenhack/go.notmuch -- -I $WORK/b033/ -g -O2 ./configList.go ./db.go ./errors.go ./filenames.go ./message.go ./messages.go ./query.go ./tag.go ./tags.go ./thread.go ./threads.go
\# github.com/zenhack/go.notmuch
\../../zenhack/go.notmuch/configList.go:9:22: fatal error: notmuch.h: No such file or directory
 // #include <notmuch.h>
                      ^
compilation terminated.
2020/05/29 11:27:20 Failed to cross compile package: exit status 2.
</code></pre>
</details>



<details>
  <summary>xgo --deps=https://notmuchmail.org/releases/LATEST-notmuch-0.29.3.tar.xz --targets=linux/amd64 -x -v .</summary>
  <pre><code>
Checking docker installation...
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Checking for required docker image karalabe/xgo-latest... found.
Dependency already cached: /Users/johannes/.xgo-cache/LATEST-notmuch-0.29.3.tar.xz.
Cross compiling github.com/JohannesKaufmann/notmuchexample...
Building locally github.com/JohannesKaufmann/notmuchexample...
Compiling for linux/amd64...
WORK=/tmp/go-build740265166
github.com/zenhack/go.notmuch
mkdir -p $WORK/b033/
cd /ext-go/1/src/github.com/zenhack/go.notmuch
CGO_LDFLAGS='"-g" "-O2" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch" "-lnotmuch"' /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/b033/ -importpath github.com/zenhack/go.notmuch -- -I $WORK/b033/ -g -O2 ./configList.go ./db.go ./errors.go ./filenames.go ./message.go ./messages.go ./query.go ./tag.go ./tags.go ./thread.go ./threads.go
\# github.com/zenhack/go.notmuch
\../../zenhack/go.notmuch/configList.go:9:22: fatal error: notmuch.h: No such file or directory
 // #include <notmuch.h>
                      ^
compilation terminated.
2020/05/29 11:39:04 Failed to cross compile package: exit status 2.
  </pre></code>
</details>

**Comment by zenhack** [comment]
hm, I get a different error:

```
Compiling for linux/amd64...
can't load package: package .: no Go files in /
2020/05/29 12:31:59 Failed to cross compile package: exit status 1.
```

This seems unlikely to be a problem with go.notmuch; we're not doing anything terribly unusual and notmuch itself is a pretty standard configure & make C package. Perhaps you could ask help from the xgo developer?

...but If it were me I'd probably just set up a one-off VM or container; since you're trying to target linux/amd64 anyway this dodges the need for an actual C cross compiler, and notmuch isn't terribly difficult to install on its own -- it doesn't seem like `xgo` is buying you enough to waste a bunch of time troubleshooting it.

**Comment by zenhack** [comment]
Going to close this, since it isn't really a go.notmuch specific issue so much a generic cross-compilation with cgo issue.
